### ISSUE TITLE
Highlight usage of Obsolete methods/classes

### ISSUE THREAD

**Issue by karelz** [terrajobst/platform-compat#1]
In both .NET Core and .NET Standard, we have legacy technologies which we do not plan to improve going forward. It's ok to use them for compat, but devs should be aware their limitations.

Example `HttpListener`, should be replaced by Kestrel and friends.

We should highlight such Obsolete APIs.

**Comment by karelz** [comment]
Dupe of #21.

**Comment by terrajobst** [comment]
Gee, you're good a keeping a clean house :-)

**Comment by karelz** [comment]
:P Mainly that was the idea from the start, you just gave it better promotion :P
