### ISSUE TITLE
Rename project

### ISSUE THREAD

**Issue by terrajobst** [terrajobst/platform-compat#16]
The acronym has some problems. Without going into too much detail:

![](https://media.giphy.com/media/TRNdMCoGkb3lS/giphy.gif)

Proposals:

* Terrajobst.CrossTargeting.Analyzers
* Terrajobst.XTargeting.Analyzers
* Terrajobst.Porting.Analyzers

Others?

**Comment by dogtail9** [comment]
Terrajobst.Porting.Analyzers! Always go for the shortest path.

**Comment by paulcbetts** [comment]
Terrajobst.NetCoreCompat.Analyzer

**Comment by dlemstra** [comment]
What about Terrajobst.CrossPlatformSupport.Analyzers? And use Terrajobst.Cps.Analyzers if you want to do less typing.

**Comment by terrajobst** [comment]
I'd like to avoid CPS as this is already in use (stands for the Common Project System, the tech that powers https://github.com/dotnet/project-system).

**Comment by dlemstra** [comment]
Too bad MS is also already taken 😄  (MultiplatformSupport)

**Comment by bradwilson** [comment]
How about `Terrajobst.Porting.Scrutinizer` so we can get our TPS reports? 😉

**Comment by Yortw** [comment]
Terrajobst.PlatformSupport.Analyzers ?

**Comment by markrendle** [comment]
NetStandardAnalyzer, or NSA for short.

**Comment by onovotny** [comment]
CrossTargeting and MultiTargeting already seem to have other connotations w.r.t. the project system with multiple TFMs.

TPS reports sounds good https://github.com/terrajobst/pns-scan/issues/16#issuecomment-292455631

**Comment by jnm2** [comment]
The problem with using the word "porting" is that it has the sense that it helps you leave one platform and singly target a new one.

**Comment by jnm2** [comment]
Terrajobst.PlatformCompat.Analyzers?

**Comment by mpoettgen** [comment]
Terrajobst.XPlatCompat.Analyzers or
Terrajobst.XPlatCompatibility.Analyzers

**Comment by terrajobst** [comment]
> Terrajobst.PlatformCompat.Analyzers

Sold.
