### ISSUE TITLE
Steer developers away from legacy/deprecated APIs

### ISSUE THREAD

**Issue by terrajobst** [terrajobst/platform-compat#21]
I'm not a fan of the obsolete attribute. The reasons are:

* **It's not contextual**. Some APIs are only problematic when used with certain values on in certain context (i.e. calling vs overriding)
* **It's in metadata**. Legacy/deprecation typically happens outside the usual shipping cycle.
* **It's very noisy**. There is no grouping, you get warnings for every single violation. Worse, you cannot easily suppress specific classes of issues, you can only suppress globally or a specific occurrence.
* **No tie-in to fixers**. Sometimes we just replace a given method with another; it would be nice to allow Roslyn-style fixers for that.

I think I could extend this tool to also cover legacy/deprecated API. For now, I'd like to gather a list of APIs so I can see what the kind of issues would look like and we'd like to surface/suppress them.

Thoughts?

**Comment by terrajobst** [comment]
My list of legacy APIs (not complete of course):

| API                     | Replacement         | Comments
|-------------------------|---------------------|-------------------
| Non-Generic collections | Generic collections | * Exclude interfaces, as they are still useful <br/> * Some tricky replacements e.g. indexer in dictionary throws
| *WebRequest             | HttpClient          |
| WebClient               | HttpClient          | No a 1:1 replacement

**Comment by jnm2** [comment]
My pet peeve is the entire `Convert` class. It blows up on use of nullable types. If my research is right, it's a class originally included only for parity with VB.NET conversions and was supposed to be superseded with `TypeConverter`. Only problem is that `TypeConverter` doesn't have a convenient static `Convert(object, Type)` method.

**Comment by JamesNK** [comment]
There needs to be an attribute for saying "this isn't being removed, and it stills works, but there is a better choice available". Uses of a type/member with the new attribute would be an information message instead of a warning at build.

e.g. IDbConnection vs DbConnection

**Comment by terrajobst** [comment]
A few more suggestions:

* SmtpClient (by @migueldeicaza)
* SecureString (by @onovotn)

**Comment by jnm2** [comment]
There's no reason not use `SecureString` on .NET Framework, is there?

**Comment by onovotny** [comment]
@jnm2 because there's no such thing as a SecureString, it's bogus :P

**Comment by jnm2** [comment]
@onovotny I've been told it significantly reduces the chance of getting the plain text paged to disk. Is that not true?

**Comment by terrajobst** [comment]
https://github.com/dotnet/apireviews/tree/master/2015/07-14-securestring#problems-with-securestring

**Comment by JamesNK** [comment]
How about recommending this Json.NET thing over JavaScriptSerializer and DataContractJsonSerializer.

MSDN docs already do https://msdn.microsoft.com/en-us/library/system.web.script.serialization.javascriptserializer 😸

**Comment by jnm2** [comment]
@terrajobst I remember that. But the points it raises were already well known with regards to the usefulness and applicability of SecureString for desktop applications. If people want to keep passwords off the physical disk and out of dumps, I don't see any reason to discourage them on .NET Framework. Showing a warning for only .NET Core makes sense because of the lack of encryption.

**Comment by karelz** [comment]
We (or at least I) have plans to use the tooling also for Desktop (.NET Framework). Primary driver is .NET Standard and .NET Core right now.

**Comment by aliostad** [comment]
My 2 cents:

> I'm not a fan of the obsolete attribute

I have found them very useful specially, in giving the right to API designers to make a serious breaking change after giving everyone *one cycle* to migrate - basically community cannot really complain why something was taken away.

> Non-Generic collections

I believe everyone stopped using them long time ago - so good riddance.

> WebRequest

Considering literally all HTTP calls underneath made by this, not sure what is meant by removing it... making it internal?

> WebClient

AFAIK, the only tool available in the framework to make FTP calls. Unless there is a replacement, cannot see how it can be dropped.

**Comment by khellang** [comment]
> There needs to be an attribute for saying "this isn't being removed, and it stills works, but there is a better choice available". Using a type or member with the new attribute on it would be an information message instead of a warning at build.

Sounds like [the proposed `LegacyAttribute`](https://github.com/dotnet/corefx/issues/10093) to me...

> Unless there is a replacement, cannot see how it can be dropped.

I don't think this is about dropping anything. It's merely anout APIs that have newer and/or better alternatives.

**Comment by bitapparat** [comment]
The behavior I'd prefer to see would be a "Notify about legacy APIs" checkbox in project settings that's on by default. If checked, declaration of legacy typed variables, initialization of legacy types, or usage of legacy members in non-legacy types would be marked with a (suppressible) information entry.

It'd be neat if legacy variables that are passed into or receive a value from a type of a third-party assembly would be excluded from this rule, to prevent a need to disable or suppress this functionality when consuming a library that expects or exposes legacy types.

**Comment by karelz** [comment]
Here's a subtle difference of `ConcurrentDictionary.ctor(...)`  (some overloads) https://github.com/dotnet/corefx/pull/18441#issuecomment-294672821

@terrajobst I need a database, please, please, please! Make it a wiki, or md file with PRs, I don't care -- or should I create it on CoreFX? (BTW: You're lucky you didn't give me write access to your repo, otherwise I would have created it myself by now 😝)

**Comment by karelz** [comment]
And another one https://github.com/dotnet/corefx/issues/14614 ... database please! Or I will steal your credentials ...

**Comment by karelz** [comment]
@terrajobst I need a place to collaborate on the list - please create one here, or give me RW access (and I can create it), or we should create one in CoreFX (wiki pages should be ok - everyone can write there without a PR). Pretty please?

**Comment by bitapparat** [comment]
@karelz This issue here is about old APIs that won't be removed, but have a superior API that should be used instead. Like List<T> being preferable to ArrayList. Your posts are about functional differences between the frameworks, which isn't the topic at hand here, and should probably be discussed in a different issue or thread.

**Comment by karelz** [comment]
@bitapparat while you are technically correct, we need both. And that's what this tool is about -- about both ;). I'll be happy to move the list into another issue. The point is, we need a central point to collect all the info.

**Comment by karelz** [comment]
FYI: After discussion with @terrajobst I created a wiki page on CoreFX: https://github.com/dotnet/corefx/wiki/ApiCompat
Anyone can edit it (no PR system), so feel free to add more stuff there

**Comment by terrajobst** [comment]
Fixed by #24
