### ISSUE TITLE
Environment.OSVersion.Platform

### ISSUE THREAD

**Issue by justinvp** [terrajobst/platform-compat#29]
Nice work, Immo!

How about a warning for `Environment.OSVersion.Platform` usage?

My main concern is with `PlatformID.MacOSX`. Back in the Silverlight days, `Environment.OSVersion.Platform` returned `PlatformID.MacOSX` on OSX. However, on .NET Core it returns `PlatformID.Unix` on macOS to match Mono's behavior.

This is already [confusing](https://forums.xamarin.com/discussion/76730/why-does-environment-osversion-return-platformid-unix-and-not-macosx) for Xamarin.Mac developers and I think it's going to be confusing for .NET Core developers as well.

Code that compares `Environment.OSVersion.Platform` to `PlatformID.MacOSX` should use the newer `RuntimeInformation.IsOSPlatform(OSPlatform.OSX)` API instead.

Note that many of the other enum values are suspect as well:

```c#
public enum PlatformID
{
    Win32S = 0,
    Win32Windows = 1,
    Win32NT = 2,
    WinCE = 3,
    Unix = 4,
    Xbox = 5,
    MacOSX = 6
}
```

Reference: https://github.com/dotnet/corefx/issues/11878

**Comment by SamuelEnglard** [comment]
This drove me nuts a bunch of years ago!
