### ISSUE TITLE
Support database entries beyond PlatformNotSupportedException

### ISSUE THREAD

**Issue by karelz** [terrajobst/platform-compat#4]
We need to manually feed the database with known differences between platforms.

I will be collecting that data on CoreFX teams - we need a way to add the info into this tool.

**Comment by terrajobst** [comment]
Yep, I should add the baseline violations form .NET Framework 4.6.1.

**Comment by karelz** [comment]
BTW: We will have other "differences" from area owners on top of that.

**Comment by terrajobst** [comment]
Fair, I've generalized the lookup quite a bit.
